/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil/router";
export namespace Components {
    interface AppRoot {
    }
    interface BusinessDetailPage {
        "match": MatchResults;
    }
    interface BusinessListPage {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLBusinessDetailPageElement extends Components.BusinessDetailPage, HTMLStencilElement {
    }
    var HTMLBusinessDetailPageElement: {
        prototype: HTMLBusinessDetailPageElement;
        new (): HTMLBusinessDetailPageElement;
    };
    interface HTMLBusinessListPageElement extends Components.BusinessListPage, HTMLStencilElement {
    }
    var HTMLBusinessListPageElement: {
        prototype: HTMLBusinessListPageElement;
        new (): HTMLBusinessListPageElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "business-detail-page": HTMLBusinessDetailPageElement;
        "business-list-page": HTMLBusinessListPageElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface BusinessDetailPage {
        "match"?: MatchResults;
    }
    interface BusinessListPage {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "business-detail-page": BusinessDetailPage;
        "business-list-page": BusinessListPage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "business-detail-page": LocalJSX.BusinessDetailPage & JSXBase.HTMLAttributes<HTMLBusinessDetailPageElement>;
            "business-list-page": LocalJSX.BusinessListPage & JSXBase.HTMLAttributes<HTMLBusinessListPageElement>;
        }
    }
}
